version: '3'
services:
  logstash:
    image: drmxxxxx/homee:LS-latest
    hostname: logstash
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m"    
    ports:
      - "5044:5000"
      - "9600:9600"
    volumes:
      - /volume1/homes/homee_ftp/Logstash:/var/log/logstash # Lokaler Pfad für LS zum speichern einer sincedb. WICHTIG! NICHT LÖSCHEN!
      - /lokaler/pfad/zu/den/csvdateien:/var/opt/logs # Hier den lokalen Pfad zu den homee Verlaufsdaten angeben

  grafana:
    image: drmxxxxx/homee:GRF-latest
    hostname: grafana
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m"    
    volumes:
      - /lokaler/Pfad/fuer/grafana:/var/lib/grafana # Hier einen lokalen Pfad angeben. Darin wird die Konfig von Grafana dauerhaft gespeichert
    ports:
      - "3000:3000"
    environment:
      - GF_PANELS_DISABLE_SANITZIE_HTML=true

  influxdb:
    image: drmxxxxx/homee:INDB-latest
    hostname: influxdb
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m"
    volumes:
      - /volume1/homes/homee_ftp/InfluxDB:/var/lib/influxdb # Hier einen lokalen Pfad für die Datanbank angeben.
