{
 "title": "homee Dashboard",
 "description": "Visualisierung von historischen Verlaufsdaten",
 "tags": [
  "homee",
  "Verlaufsdaten"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Allgemein", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aktuelle Uhrzeit",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "content": "<a class=\"weatherwidget-io\" href=\"https://forecast7.com/de/48d2116d37/vienna/\" data-label_1=\"Wien\" data-label_2=\"Wetter\" data-icons=\"Climacons\" data-theme=\"dark\" >Wetter Wien</a>\n<script>\n!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');\n</script>",
   "targets": [
    { "target": "temperatureHigh", "type": "timeseries" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "homee",
     "query": "SHOW TAG VALUES WITH KEY = device",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batteriestatus",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "verlaufsdaten",
     "query": "SELECT last(\"value\") FROM \"homee\" WHERE (\"metrix\" = 'Batterieladung') AND $timeFilter GROUP BY \"device\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Batterieladung" }
     ]
    }
   ]
  },
  { "title": "Bewegungsdaten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Bewegungsalarm",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Bewegungsalarm" }
     ]
    }
   ]
  },
  {
   "title": "Manipulationsalarm",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Manipulationsalarm" }
     ]
    }
   ]
  },
  { "title": "Energie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Spannung und Stromstärke",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "volt", "label": "Spannung" }
   ],
   "targets": [
    {
     "alias": "$tag_device (v)",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Spannung" }
     ]
    },
    {
     "alias": "$tag_device (amp)",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Stromstärke" }
     ]
    }
   ]
  },
  {
   "title": "Aktueller Verbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Aktueller Verbrauch" }
     ]
    }
   ]
  },
  {
   "title": "Summierter Verbrauch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Summierter Verbrauch" }
     ]
    }
   ]
  },
  {
   "title": "Summierter Verbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Summierter Verbrauch" }
     ]
    }
   ]
  },
  { "title": "Raumklima", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Höchsttemperatur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Temperatur" }
     ]
    }
   ]
  },
  {
   "title": "Temperaturen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Temperatur" }
     ]
    }
   ]
  },
  {
   "title": "Helligkeit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Helligkeit" }
     ]
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "verlaufsdaten",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metrix", "operator": "=", "value": "Relative Luftfeuchtigkeit" }
     ]
    }
   ]
  }
 ]
}