FROM influxdb:1.7.10-alpine

ENV INFLUXDB_DB=verlaufsdaten \
    INFLUXDB_ADMIN_USER=admin \
    INFLUXDB_ADMIN_PASSWORD=homeeDB_admin \
    INFLUXDB_USER=user \
    INFLUXDB_USER_PASSWORD=homeeDB_user \